import 'package:project_smm/entities/reports_entities/types/structure_report_table.dart';
import 'package:project_smm/entities/types/reports_model/reports_model.dart';

List<StructureReportTable> getReportList(ReportsModel reportsModel) {
  return [
    StructureReportTable(false, 'Обращений', reportsModel.yesterday!.all,
        reportsModel.today!.all, reportsModel.today!.all),
    StructureReportTable(
        false,
        'Повторные',
        reportsModel.yesterday!.repeats.value,
        reportsModel.today!.repeats.value,
        reportsModel.today!.repeats.percent),
    StructureReportTable(
        false,
        'Без выезда',
        reportsModel.yesterday!.withoutTransit.value,
        reportsModel.today!.withoutTransit.value,
        reportsModel.today!.withoutTransit.value),
    StructureReportTable(
        false,
        'Безрезультатных',
        reportsModel.yesterday!.withoutResult.value,
        reportsModel.today!.withoutResult.value,
        reportsModel.today!.withoutResult.value),
    StructureReportTable(
        false,
        'Всего выездов',
        reportsModel.yesterday!.withTransit.all.value,
        reportsModel.today!.withTransit.all.value,
        reportsModel.today!.withTransit.all.value),
    StructureReportTable(
        true,
        '1-3 срочность',
        reportsModel.yesterday!.withTransit.firstThirdPriority.value,
        reportsModel.today!.withTransit.firstThirdPriority.value,
        reportsModel.today!.withTransit.firstThirdPriority.percent),
    StructureReportTable(
        true,
        '4 срочность',
        reportsModel.yesterday!.withTransit.fourthPriority.value,
        reportsModel.today!.withTransit.fourthPriority.value,
        reportsModel.today!.withTransit.fourthPriority.percent),
    StructureReportTable(
        true,
        'Другое',
        reportsModel.yesterday!.withTransit.other.value,
        reportsModel.today!.withTransit.other.value,
        reportsModel.today!.withTransit.other.percent),
    StructureReportTable(
        false,
        '1 срочность',
        reportsModel.yesterday!.firstPriority.all.value,
        reportsModel.today!.firstPriority.all.value,
        reportsModel.today!.firstPriority.all.percent),
    StructureReportTable(
        true,
        'Оперативность',
        reportsModel.yesterday!.firstPriority.efficiency.value,
        reportsModel.today!.firstPriority.efficiency.value,
        reportsModel.today!.firstPriority.efficiency.percent),
    StructureReportTable(
        false,
        '2 срочность',
        reportsModel.yesterday!.secondPriority.all.value,
        reportsModel.today!.secondPriority.all.value,
        reportsModel.today!.secondPriority.all.percent),
    StructureReportTable(
        true,
        'Оперативность',
        reportsModel.yesterday!.secondPriority.efficiency.value,
        reportsModel.today!.secondPriority.efficiency.value,
        reportsModel.today!.secondPriority.efficiency.percent),
    StructureReportTable(
        false,
        '3 срочность',
        reportsModel.yesterday!.thirdPriority.all.value,
        reportsModel.today!.thirdPriority.all.value,
        reportsModel.today!.thirdPriority.all.percent),
    StructureReportTable(
        true,
        'Оперативность',
        reportsModel.yesterday!.thirdPriority.efficiency.value,
        reportsModel.today!.thirdPriority.efficiency.value,
        reportsModel.today!.thirdPriority.efficiency.percent),
    StructureReportTable(
        false,
        '4 срочность',
        reportsModel.yesterday!.fourthPriority.all.value,
        reportsModel.today!.fourthPriority.all.value,
        reportsModel.today!.fourthPriority.all.percent),
    StructureReportTable(
        true,
        'Оперативность',
        reportsModel.yesterday!.fourthPriority.efficiency.value,
        reportsModel.today!.fourthPriority.efficiency.value,
        reportsModel.today!.fourthPriority.efficiency.percent),
    StructureReportTable(
        false,
        'Среднее время оказания помощи',
        reportsModel.yesterday!.avgHealTime.value.toInt(),
        reportsModel.today!.avgHealTime.value.toInt(),
        0),
    StructureReportTable(
        true,
        'ОССМП',
        reportsModel.yesterday!.avgHealTime.polyclinicValue.toInt(),
        reportsModel.today!.avgHealTime.polyclinicValue.toInt(),
        0),
    StructureReportTable(
        true,
        'СМП при ПМСП',
        reportsModel.yesterday!.avgHealTime.noPolyclinicValue.toInt(),
        reportsModel.today!.avgHealTime.noPolyclinicValue.toInt(),
        0),
    StructureReportTable(
        false,
        'Среднее время доезда',
        reportsModel.yesterday!.avgArriveTime.value.toInt(),
        reportsModel.today!.avgArriveTime.value.toInt(),
        0),
    StructureReportTable(
        true,
        'ОССМП',
        reportsModel.yesterday!.avgArriveTime.polyclinicValue.toInt(),
        reportsModel.today!.avgArriveTime.polyclinicValue.toInt(),
        0),
    StructureReportTable(
        true,
        'СМП при ПМСП',
        reportsModel.yesterday!.avgArriveTime.noPolyclinicValue.toInt(),
        reportsModel.today!.avgArriveTime.noPolyclinicValue.toInt(),
        0),
    StructureReportTable(
        false,
        'Доставлены в МО',
        reportsModel.yesterday!.transitToMoCalls.all.value,
        reportsModel.today!.transitToMoCalls.all.value,
        reportsModel.today!.transitToMoCalls.all.percent),
    StructureReportTable(
        true,
        'на госпитализацию',
        reportsModel.yesterday!.transitToMoCalls.hospitalization.value,
        reportsModel.today!.transitToMoCalls.hospitalization.value,
        reportsModel.today!.transitToMoCalls.hospitalization.percent),
    StructureReportTable(
        true,
        'для оказания помощи',
        reportsModel.yesterday!.transitToMoCalls.help.value,
        reportsModel.today!.transitToMoCalls.help.value,
        reportsModel.today!.transitToMoCalls.help.percent),
    StructureReportTable(
        true,
        'Прочие',
        reportsModel.yesterday!.transitToMoCalls.other.value,
        reportsModel.today!.transitToMoCalls.other.value,
        reportsModel.today!.transitToMoCalls.other.percent),
    StructureReportTable(
        false,
        'Вызова по ЧС',
        reportsModel.yesterday!.emergency.value,
        reportsModel.today!.emergency.value,
        reportsModel.today!.emergency.percent),
    StructureReportTable(
        false,
        'Летальность',
        reportsModel.yesterday!.lethal.all.value,
        reportsModel.today!.lethal.all.value,
        reportsModel.today!.lethal.all.percent),
    StructureReportTable(
        true,
        'до СМП',
        reportsModel.yesterday!.lethal.beforeSmp.value,
        reportsModel.today!.lethal.beforeSmp.value,
        reportsModel.today!.lethal.beforeSmp.percent),
    StructureReportTable(
        true,
        'При СМП/В машине СМП',
        reportsModel.yesterday!.lethal.afterSmp.value,
        reportsModel.today!.lethal.afterSmp.value,
        reportsModel.today!.lethal.afterSmp.percent),
    StructureReportTable(
        false,
        'Реанимация',
        reportsModel.yesterday!.reanimation.all.value,
        reportsModel.today!.reanimation.all.value,
        reportsModel.today!.reanimation.all.percent),
    StructureReportTable(
        true,
        'успешная',
        reportsModel.yesterday!.reanimation.success.value,
        reportsModel.today!.reanimation.success.value,
        reportsModel.today!.reanimation.success.percent),
    StructureReportTable(
        true,
        'безуспешная',
        reportsModel.yesterday!.reanimation.failed.value,
        reportsModel.today!.reanimation.failed.value,
        reportsModel.today!.reanimation.failed.percent),
    StructureReportTable(
        false,
        'ШОКИ',
        reportsModel.yesterday!.shock.value,
        reportsModel.today!.shock.value,
        reportsModel.today!.shock.percent),
    StructureReportTable(
        false,
        'ОКС',
        reportsModel.yesterday!.oks.all.value,
        reportsModel.today!.oks.all.value,
        reportsModel.today!.oks.all.percent),
    StructureReportTable(
        true,
        'с подъёмом ST',
        reportsModel.yesterday!.oks.withUpSt.value,
        reportsModel.today!.oks.withUpSt.value,
        reportsModel.today!.oks.withUpSt.percent),
    StructureReportTable(
        true,
        'без подъёма ST',
        reportsModel.yesterday!.oks.withoutUpSt.value,
        reportsModel.today!.oks.withoutUpSt.value,
        reportsModel.today!.oks.withoutUpSt.percent),
    StructureReportTable(
        false,
        'ОНМК',
        reportsModel.yesterday!.onmk.all.value,
        reportsModel.today!.onmk.all.value,
        reportsModel.today!.onmk.all.percent),
    StructureReportTable(
        true,
        'в течении 40 минут',
        reportsModel.yesterday!.onmk.lt40Min.value,
        reportsModel.today!.onmk.lt40Min.value,
        reportsModel.today!.onmk.lt40Min.percent),
    StructureReportTable(
        true,
        'более 40 минут',
        reportsModel.yesterday!.onmk.gt40Min.value,
        reportsModel.today!.onmk.gt40Min.value,
        reportsModel.today!.onmk.gt40Min.percent),
    StructureReportTable(
        false,
        'Беременные',
        reportsModel.yesterday!.pregnancy.all.value,
        reportsModel.today!.pregnancy.all.value,
        reportsModel.today!.pregnancy.all.percent),
    StructureReportTable(
        true,
        'отказ от госпитализации',
        reportsModel.yesterday!.pregnancy.hospitalizationRefuse.value,
        reportsModel.today!.pregnancy.hospitalizationRefuse.value,
        reportsModel.today!.pregnancy.hospitalizationRefuse.percent),
    StructureReportTable(
        true,
        'Преэклампсии или эклампсии',
        reportsModel.yesterday!.pregnancy.eclampsia.value,
        reportsModel.today!.pregnancy.eclampsia.value,
        reportsModel.today!.pregnancy.eclampsia.percent),
    StructureReportTable(
        true,
        'домашние/дорожные роды',
        reportsModel.yesterday!.pregnancy.home.value,
        reportsModel.today!.pregnancy.home.value,
        reportsModel.today!.pregnancy.home.percent),
    StructureReportTable(
        false,
        'ОРВИ/пневмонии',
        reportsModel.yesterday!.orvi.value,
        reportsModel.today!.orvi.value,
        reportsModel.today!.orvi.percent),
    StructureReportTable(
        false,
        'Инфекции',
        reportsModel.yesterday!.infection.value,
        reportsModel.today!.infection.value,
        reportsModel.today!.infection.percent),
  ];
}